#CODIGO PARA LA ABUNDANCIA Y LA DENCIDAD TOTAL Y POR ESPECIE



ABUNDANCIA_DENCIDAD_ESPECIES<-function(NOMBRE_CIENTIFICO,TOTAL_AVISTAMIENTOS,AVISTAMIENTOS_DENTRO_DEL_RADIO,AVISTAMIENTOS_FUERA_DEL_RADIO,SUPERFICIE,CONTEOS){
  
  #agrupacion de datos en funcion con el nombre cientifico y eliminacion de datos nulo
  
  datos<-data.frame(NOMBRE_CIENTIFICO,TOTAL_AVISTAMIENTOS,AVISTAMIENTOS_DENTRO_DEL_RADIO,AVISTAMIENTOS_FUERA_DEL_RADIO)
  
  datos<-datos%>%group_by(NOMBRE_CIENTIFICO)
  
  #datos[is.na(datos)]<-0     #SE DEBE DE UTILIZAR SI EXISTEN DATOS NULOS QUE SEAN CONSIDERADOS COMO SIN AVISTAMIENTOS
  
  #suma de los datos en funcion del nombre cientifico
  
  datos<-datos%>%summarise(ABUNDANCIA=sum(TOTAL_AVISTAMIENTOS),DENTRO_RADIO=sum(AVISTAMIENTOS_DENTRO_DEL_RADIO),FUERA_DEL_RADIO=sum(AVISTAMIENTOS_FUERA_DEL_RADIO))
  
  #calculo de la abundacia relativa del inventario
  
  ABUNDANCIA_ESP<-data.frame(ESPECIE=datos$NOMBRE_CIENTIFICO,ABUNDANCIA=datos$ABUNDANCIA)
  
  total_avistamientos<-sum(ABUNDANCIA_ESP$ABUNDANCIA)
  
  ABUND_REL<-(ABUNDANCIA_ESP$ABUNDANCIA/total_avistamientos)*100
  
  ABUNDANCIA_ESP<-data.frame(ABUNDANCIA_ESP,'ABUNDANCIA RELATIVA'=as.numeric(ABUND_REL))
  
  
  #densidad poblacional por doble banda 
  
  DENSIDAD_DOBLE_BANDA<-filter(datos,DENTRO_RADIO>=1&FUERA_DEL_RADIO>=1)
  
  DENSIDAD=log(DENSIDAD_DOBLE_BANDA$ABUNDANCIA/DENSIDAD_DOBLE_BANDA$FUERA_DEL_RADIO)*(DENSIDAD_DOBLE_BANDA$ABUNDANCIA/(592*2827.4333))#CONTEOS*SUPERFICIE
  
  DENSIDAD<-DENSIDAD*10000
  
  DENSIDAD_DOBLE_BANDA<-data.frame(DENSIDAD_DOBLE_BANDA$NOMBRE_CIENTIFICO,DENSIDAD)
  
  colnames(DENSIDAD_DOBLE_BANDA)<-c("NOMBRE CIENTIFICO","DENSIDAD DOBLE BANDA/has")
  
  #dencidad por radio definido
  
  DENSIDAD_RADIO_DEFINIDO<-filter(datos,DENTRO_RADIO>=1)
  
  DENSIDAD<-DENSIDAD_RADIO_DEFINIDO$DENTRO_RADIO/(SUPERFICIE*CONTEOS)#CONTEOS*SUPERFICIE
  
  DENSIDAD<-DENSIDAD*10000
  
  DENSIDAD_RADIO_DEFINIDO<-data.frame(DENSIDAD_RADIO_DEFINIDO$NOMBRE_CIENTIFICO,DENSIDAD)
  
  colnames(DENSIDAD_RADIO_DEFINIDO)<-c("NOMBRE CIENTIFICO","DENSIDAD RADIO DEFINIDO/has")
  
  #agrupacion de datos por en una lista
  
  RESULTADOS<-list(ABUNDANCIA_ESP,DENSIDAD_DOBLE_BANDA,DENSIDAD_RADIO_DEFINIDO)
  
  names(RESULTADOS)<-c("ABUNDACIA","DENSIDAD_DOBLE_BANDA","DENSIDAD_RADIO_DEFINIDO")
  
  return(RESULTADOS)
  
}
