#densidad y abundacia segun los punto de observacion fijados en el inventario de avifauna


ABUNDANCIA_DENCIDAD_PUNTO_OBSERVACION<-function(PUNTO_DE_OBSERVACION,TOTAL_AVISTAMIENTOS,AVISTAMIENTOS_DENTRO_DEL_RADIO,AVISTAMIENTOS_FUERA_DEL_RADIO,SUPERFICIE,CONTEOS){
  
  
  datos<-data.frame(PUNTO_DE_OBSERVACION,TOTAL_AVISTAMIENTOS,AVISTAMIENTOS_DENTRO_DEL_RADIO,AVISTAMIENTOS_FUERA_DEL_RADIO)
  
  datos<-datos%>%group_by(PUNTO_DE_OBSERVACION)%>%summarise(AVISTAMINETOS=length(TOTAL_AVISTAMIENTOS),DENTRO_RADIO=sum(AVISTAMIENTOS_DENTRO_DEL_RADIO),FUERA_RADIO=sum(AVISTAMIENTOS_FUERA_DEL_RADIO),
                                                TOTAL_AVISTAMIENTOS=sum(TOTAL_AVISTAMIENTOS))
  
  ABUNDANCIA<-data.frame('PUNTO DE OBSERVACION'=datos$PUNTO_DE_OBSERVACION,ABUNDANCIA=datos$TOTAL_AVISTAMIENTOS)
  
  DENSIDAD_RADIO_DEFINIDO<-data.frame('PUNTO DE OBSERVACION'=datos$PUNTO_DE_OBSERVACION,'DENSIDAD RADIO DEFINIDO'=(datos$TOTAL_AVISTAMIENTOS/(SUPERFICIE*CONTEOS)*10000))
  
  DENSIDAD_DOBLE_BANDA<-data.frame('PUNTO DE OBSERVACION'=datos$PUNTO_DE_OBSERVACION,'DENSIDAD DOBLE BANDAD'=
                                     log(datos$TOTAL_AVISTAMIENTOS/datos$FUERA_RADIO)*(datos$TOTAL_AVISTAMIENTOS/(SUPERFICIE*CONTEOS)*10000))
  
  
  resultados<-list(ABUNDANCIA,DENSIDAD_RADIO_DEFINIDO,DENSIDAD_DOBLE_BANDA)
  
  return(resultados)
}